name: Generate Snake

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated Snake Animation"
          branch: output
          file_pattern: github-contribution-grid-snake.svg
          token: ${{ secrets.PAT }}
